version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: SchoolsTips
    restart: always
    environment:
      POSTGRES_DB: SchoolsTips
      POSTGRES_USER: Api-SchoolsTips
      POSTGRES_PASSWORD: Api-SchoolsTips
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: camila@nestjs.com
      PGADMIN_DEFAULT_PASSWORD: cami2002
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db
